/**
 * CloudFormation Template Generator
 * Generates AWS CloudFormation templates based on repository analysis
 */

import { AnalysisResult } from '@/lib/repo-analysis/analyzer';

interface CloudFormationTemplate {
  AWSTemplateFormatVersion: string;
  Description: string;
  Parameters: Record<string, CloudFormationParameter>;
  Resources: Record<string, CloudFormationResource>;
  Outputs: Record<string, CloudFormationOutput>;
}

interface CloudFormationParameter {
  Type: string;
  Description: string;
  Default?: string;
  NoEcho?: boolean;
  AllowedValues?: string[];
}

interface CloudFormationResource {
  Type: string;
  Properties: Record<string, unknown>;
  DependsOn?: string | string[];
}

interface CloudFormationOutput {
  Description: string;
  Value: unknown;
  Export?: { Name: unknown };
}

/**
 * Generate a CloudFormation template from analysis results
 */
export function generateCloudFormationTemplate(analysis: AnalysisResult): string {
  const template: CloudFormationTemplate = {
    AWSTemplateFormatVersion: '2010-09-09',
    Description: `Infrastructure for ${analysis.owner}/${analysis.repoName} - Generated by DeveloperLabs`,
    Parameters: generateParameters(analysis),
    Resources: generateResources(analysis),
    Outputs: generateOutputs(analysis),
  };

  return toYaml(template);
}

/**
 * Sanitize parameter name to be CloudFormation-compliant
 * CloudFormation parameter names must be alphanumeric (no underscores, hyphens, etc.)
 *
 * Examples:
 * - NODE_ENV → NodeEnv
 * - DATABASE_URL → DatabaseUrl
 * - AWS_ACCESS_KEY_ID → AwsAccessKeyId
 */
function sanitizeParameterName(name: string): string {
  // Split by underscore and convert to PascalCase
  return name
    .split('_')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('');
}

/**
 * Generate parameters section
 */
function generateParameters(analysis: AnalysisResult): Record<string, CloudFormationParameter> {
  const params: Record<string, CloudFormationParameter> = {
    Environment: {
      Type: 'String',
      Description: 'Deployment environment',
      Default: 'production',
      AllowedValues: ['development', 'staging', 'production'],
    },
    VpcId: {
      Type: 'AWS::EC2::VPC::Id',
      Description: 'VPC ID for deployment',
    },
    SubnetIds: {
      Type: 'List<AWS::EC2::Subnet::Id>',
      Description: 'Subnet IDs for deployment',
    },
  };

  // Add environment variables as parameters
  for (const envVar of analysis.envVars) {
    const isSecret = envVar.name.includes('SECRET') ||
                     envVar.name.includes('KEY') ||
                     envVar.name.includes('PASSWORD') ||
                     envVar.name.includes('TOKEN');

    // Use sanitized parameter name (CloudFormation requires alphanumeric names)
    const paramName = sanitizeParameterName(envVar.name);

    params[paramName] = {
      Type: 'String',
      Description: `${envVar.description} (${envVar.name})`, // Include original name in description
      ...(isSecret && { NoEcho: true }),
      ...(envVar.defaultValue && { Default: envVar.defaultValue }),
    };
  }

  return params;
}

/**
 * Generate resources section based on recommended AWS services
 */
function generateResources(analysis: AnalysisResult): Record<string, CloudFormationResource> {
  const resources: Record<string, CloudFormationResource> = {};

  // Always add security group
  resources.ApplicationSecurityGroup = {
    Type: 'AWS::EC2::SecurityGroup',
    Properties: {
      GroupDescription: `Security group for ${analysis.repoName}`,
      VpcId: { Ref: 'VpcId' },
      SecurityGroupIngress: [
        {
          IpProtocol: 'tcp',
          FromPort: 443,
          ToPort: 443,
          CidrIp: '0.0.0.0/0',
        },
        {
          IpProtocol: 'tcp',
          FromPort: 80,
          ToPort: 80,
          CidrIp: '0.0.0.0/0',
        },
      ],
      Tags: [{ Key: 'Name', Value: { 'Fn::Sub': '${Environment}-${AWS::StackName}-sg' } }],
    },
  };

  // Add resources based on recommended services
  for (const service of analysis.awsServices) {
    const serviceLower = service.service.toLowerCase();

    if (serviceLower.includes('ecs') || serviceLower.includes('fargate')) {
      addECSResources(resources, analysis);
    } else if (serviceLower.includes('lambda')) {
      addLambdaResources(resources, analysis);
    } else if (serviceLower.includes('rds')) {
      addRDSResources(resources, analysis);
    } else if (serviceLower.includes('dynamodb')) {
      addDynamoDBResources(resources, analysis);
    } else if (serviceLower.includes('elasticache') || serviceLower.includes('redis')) {
      addElastiCacheResources(resources, analysis);
    } else if (serviceLower.includes('s3')) {
      addS3Resources(resources, analysis);
    } else if (serviceLower.includes('cloudfront')) {
      addCloudFrontResources(resources, analysis);
    } else if (serviceLower.includes('alb') || serviceLower.includes('load balancer')) {
      addALBResources(resources, analysis);
    } else if (serviceLower.includes('secrets manager')) {
      addSecretsManagerResources(resources, analysis);
    }
  }

  return resources;
}

/**
 * Add ECS Fargate resources
 */
function addECSResources(resources: Record<string, CloudFormationResource>, analysis: AnalysisResult): void {
  // ECS Cluster
  resources.ECSCluster = {
    Type: 'AWS::ECS::Cluster',
    Properties: {
      ClusterName: { 'Fn::Sub': '${Environment}-${AWS::StackName}-cluster' },
      CapacityProviders: ['FARGATE', 'FARGATE_SPOT'],
      DefaultCapacityProviderStrategy: [
        { CapacityProvider: 'FARGATE', Weight: 1, Base: 1 },
      ],
    },
  };

  // Task Execution Role
  resources.TaskExecutionRole = {
    Type: 'AWS::IAM::Role',
    Properties: {
      AssumeRolePolicyDocument: {
        Version: '2012-10-17',
        Statement: [{
          Effect: 'Allow',
          Principal: { Service: 'ecs-tasks.amazonaws.com' },
          Action: 'sts:AssumeRole',
        }],
      },
      ManagedPolicyArns: [
        'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy',
      ],
    },
  };

  // Task Role
  resources.TaskRole = {
    Type: 'AWS::IAM::Role',
    Properties: {
      AssumeRolePolicyDocument: {
        Version: '2012-10-17',
        Statement: [{
          Effect: 'Allow',
          Principal: { Service: 'ecs-tasks.amazonaws.com' },
          Action: 'sts:AssumeRole',
        }],
      },
    },
  };

  // Task Definition
  // Map environment variables to use sanitized parameter names for Ref
  const envVars = analysis.envVars.map(v => ({
    Name: v.name, // Keep original name for container environment
    Value: { Ref: sanitizeParameterName(v.name) }, // Use sanitized name for parameter reference
  }));

  resources.TaskDefinition = {
    Type: 'AWS::ECS::TaskDefinition',
    Properties: {
      Family: { 'Fn::Sub': '${Environment}-${AWS::StackName}' },
      Cpu: '512',
      Memory: '1024',
      NetworkMode: 'awsvpc',
      RequiresCompatibilities: ['FARGATE'],
      ExecutionRoleArn: { 'Fn::GetAtt': ['TaskExecutionRole', 'Arn'] },
      TaskRoleArn: { 'Fn::GetAtt': ['TaskRole', 'Arn'] },
      ContainerDefinitions: [{
        Name: analysis.repoName,
        Image: { 'Fn::Sub': '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Environment}-${AWS::StackName}:latest' },
        PortMappings: [{ ContainerPort: 3000, Protocol: 'tcp' }],
        Environment: envVars,
        LogConfiguration: {
          LogDriver: 'awslogs',
          Options: {
            'awslogs-group': { Ref: 'LogGroup' },
            'awslogs-region': { Ref: 'AWS::Region' },
            'awslogs-stream-prefix': 'ecs',
          },
        },
      }],
    },
  };

  // Log Group
  resources.LogGroup = {
    Type: 'AWS::Logs::LogGroup',
    Properties: {
      LogGroupName: { 'Fn::Sub': '/ecs/${Environment}-${AWS::StackName}' },
      RetentionInDays: 30,
    },
  };

  // ECS Service
  resources.ECSService = {
    Type: 'AWS::ECS::Service',
    DependsOn: 'ALBListener',
    Properties: {
      ServiceName: { 'Fn::Sub': '${Environment}-${AWS::StackName}-service' },
      Cluster: { Ref: 'ECSCluster' },
      TaskDefinition: { Ref: 'TaskDefinition' },
      DesiredCount: 2,
      LaunchType: 'FARGATE',
      NetworkConfiguration: {
        AwsvpcConfiguration: {
          AssignPublicIp: 'ENABLED',
          SecurityGroups: [{ Ref: 'ApplicationSecurityGroup' }],
          Subnets: { Ref: 'SubnetIds' },
        },
      },
      LoadBalancers: [{
        ContainerName: analysis.repoName,
        ContainerPort: 3000,
        TargetGroupArn: { Ref: 'TargetGroup' },
      }],
    },
  };
}

/**
 * Add Lambda resources
 */
function addLambdaResources(resources: Record<string, CloudFormationResource>, analysis: AnalysisResult): void {
  resources.LambdaExecutionRole = {
    Type: 'AWS::IAM::Role',
    Properties: {
      AssumeRolePolicyDocument: {
        Version: '2012-10-17',
        Statement: [{
          Effect: 'Allow',
          Principal: { Service: 'lambda.amazonaws.com' },
          Action: 'sts:AssumeRole',
        }],
      },
      ManagedPolicyArns: [
        'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole',
      ],
    },
  };

  resources.LambdaFunction = {
    Type: 'AWS::Lambda::Function',
    Properties: {
      FunctionName: { 'Fn::Sub': '${Environment}-${AWS::StackName}' },
      Runtime: 'nodejs18.x',
      Handler: 'index.handler',
      Role: { 'Fn::GetAtt': ['LambdaExecutionRole', 'Arn'] },
      MemorySize: 256,
      Timeout: 30,
      Environment: {
        Variables: Object.fromEntries(
          analysis.envVars.map(v => [v.name, { Ref: v.name }])
        ),
      },
    },
  };
}

/**
 * Add RDS resources
 */
function addRDSResources(resources: Record<string, CloudFormationResource>, analysis: AnalysisResult): void {
  const dbType = analysis.databases[0]?.type || 'PostgreSQL';
  const engine = dbType.toLowerCase().includes('mysql') ? 'mysql' : 'postgres';

  resources.DBSubnetGroup = {
    Type: 'AWS::RDS::DBSubnetGroup',
    Properties: {
      DBSubnetGroupDescription: `Subnet group for ${analysis.repoName}`,
      SubnetIds: { Ref: 'SubnetIds' },
    },
  };

  resources.DBSecurityGroup = {
    Type: 'AWS::EC2::SecurityGroup',
    Properties: {
      GroupDescription: `Database security group for ${analysis.repoName}`,
      VpcId: { Ref: 'VpcId' },
      SecurityGroupIngress: [{
        IpProtocol: 'tcp',
        FromPort: engine === 'postgres' ? 5432 : 3306,
        ToPort: engine === 'postgres' ? 5432 : 3306,
        SourceSecurityGroupId: { Ref: 'ApplicationSecurityGroup' },
      }],
    },
  };

  resources.RDSInstance = {
    Type: 'AWS::RDS::DBInstance',
    Properties: {
      DBInstanceIdentifier: { 'Fn::Sub': '${Environment}-${AWS::StackName}-db' },
      DBInstanceClass: 'db.t3.micro',
      Engine: engine,
      EngineVersion: engine === 'postgres' ? '15' : '8.0',
      AllocatedStorage: '20',
      StorageType: 'gp2',
      MasterUsername: 'admin',
      MasterUserPassword: { Ref: 'DATABASE_URL' },
      DBSubnetGroupName: { Ref: 'DBSubnetGroup' },
      VPCSecurityGroups: [{ Ref: 'DBSecurityGroup' }],
      PubliclyAccessible: false,
      MultiAZ: false,
      DeletionProtection: true,
    },
  };
}

/**
 * Add DynamoDB resources
 */
function addDynamoDBResources(resources: Record<string, CloudFormationResource>, analysis: AnalysisResult): void {
  resources.DynamoDBTable = {
    Type: 'AWS::DynamoDB::Table',
    Properties: {
      TableName: { 'Fn::Sub': '${Environment}-${AWS::StackName}' },
      AttributeDefinitions: [
        { AttributeName: 'pk', AttributeType: 'S' },
        { AttributeName: 'sk', AttributeType: 'S' },
      ],
      KeySchema: [
        { AttributeName: 'pk', KeyType: 'HASH' },
        { AttributeName: 'sk', KeyType: 'RANGE' },
      ],
      BillingMode: 'PAY_PER_REQUEST',
      PointInTimeRecoverySpecification: { PointInTimeRecoveryEnabled: true },
    },
  };
}

/**
 * Add ElastiCache resources
 */
function addElastiCacheResources(resources: Record<string, CloudFormationResource>, analysis: AnalysisResult): void {
  resources.ElastiCacheSubnetGroup = {
    Type: 'AWS::ElastiCache::SubnetGroup',
    Properties: {
      Description: `Subnet group for ${analysis.repoName} cache`,
      SubnetIds: { Ref: 'SubnetIds' },
    },
  };

  resources.ElastiCacheSecurityGroup = {
    Type: 'AWS::EC2::SecurityGroup',
    Properties: {
      GroupDescription: `Cache security group for ${analysis.repoName}`,
      VpcId: { Ref: 'VpcId' },
      SecurityGroupIngress: [{
        IpProtocol: 'tcp',
        FromPort: 6379,
        ToPort: 6379,
        SourceSecurityGroupId: { Ref: 'ApplicationSecurityGroup' },
      }],
    },
  };

  resources.ElastiCacheCluster = {
    Type: 'AWS::ElastiCache::CacheCluster',
    Properties: {
      ClusterName: { 'Fn::Sub': '${Environment}-${AWS::StackName}-cache' },
      CacheNodeType: 'cache.t3.micro',
      Engine: 'redis',
      NumCacheNodes: 1,
      CacheSubnetGroupName: { Ref: 'ElastiCacheSubnetGroup' },
      VpcSecurityGroupIds: [{ Ref: 'ElastiCacheSecurityGroup' }],
    },
  };
}

/**
 * Add S3 resources
 */
function addS3Resources(resources: Record<string, CloudFormationResource>, analysis: AnalysisResult): void {
  resources.S3Bucket = {
    Type: 'AWS::S3::Bucket',
    Properties: {
      BucketName: { 'Fn::Sub': '${Environment}-${AWS::StackName}-assets-${AWS::AccountId}' },
      PublicAccessBlockConfiguration: {
        BlockPublicAcls: true,
        BlockPublicPolicy: true,
        IgnorePublicAcls: true,
        RestrictPublicBuckets: true,
      },
      BucketEncryption: {
        ServerSideEncryptionConfiguration: [{
          ServerSideEncryptionByDefault: { SSEAlgorithm: 'AES256' },
        }],
      },
      VersioningConfiguration: { Status: 'Enabled' },
    },
  };
}

/**
 * Add CloudFront resources
 */
function addCloudFrontResources(resources: Record<string, CloudFormationResource>, analysis: AnalysisResult): void {
  resources.CloudFrontDistribution = {
    Type: 'AWS::CloudFront::Distribution',
    Properties: {
      DistributionConfig: {
        Enabled: true,
        DefaultRootObject: 'index.html',
        Origins: [{
          Id: 'S3Origin',
          DomainName: { 'Fn::GetAtt': ['S3Bucket', 'RegionalDomainName'] },
          S3OriginConfig: {
            OriginAccessIdentity: '',
          },
        }],
        DefaultCacheBehavior: {
          TargetOriginId: 'S3Origin',
          ViewerProtocolPolicy: 'redirect-to-https',
          CachePolicyId: '658327ea-f89d-4fab-a63d-7e88639e58f6', // CachingOptimized
        },
        PriceClass: 'PriceClass_100',
      },
    },
  };
}

/**
 * Add ALB resources
 */
function addALBResources(resources: Record<string, CloudFormationResource>, analysis: AnalysisResult): void {
  resources.ALB = {
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer',
    Properties: {
      Name: { 'Fn::Sub': '${Environment}-${AWS::StackName}-alb' },
      Type: 'application',
      Scheme: 'internet-facing',
      SecurityGroups: [{ Ref: 'ApplicationSecurityGroup' }],
      Subnets: { Ref: 'SubnetIds' },
    },
  };

  resources.TargetGroup = {
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup',
    Properties: {
      Name: { 'Fn::Sub': '${Environment}-${AWS::StackName}-tg' },
      Port: 3000,
      Protocol: 'HTTP',
      TargetType: 'ip',
      VpcId: { Ref: 'VpcId' },
      HealthCheckPath: '/health',
      HealthCheckIntervalSeconds: 30,
    },
  };

  resources.ALBListener = {
    Type: 'AWS::ElasticLoadBalancingV2::Listener',
    Properties: {
      LoadBalancerArn: { Ref: 'ALB' },
      Port: 80,
      Protocol: 'HTTP',
      DefaultActions: [{
        Type: 'forward',
        TargetGroupArn: { Ref: 'TargetGroup' },
      }],
    },
  };
}

/**
 * Add Secrets Manager resources
 */
function addSecretsManagerResources(resources: Record<string, CloudFormationResource>, analysis: AnalysisResult): void {
  resources.ApplicationSecrets = {
    Type: 'AWS::SecretsManager::Secret',
    Properties: {
      Name: { 'Fn::Sub': '${Environment}/${AWS::StackName}/secrets' },
      Description: `Secrets for ${analysis.repoName}`,
      SecretString: JSON.stringify(
        Object.fromEntries(
          analysis.envVars
            .filter(v => v.name.includes('SECRET') || v.name.includes('KEY') || v.name.includes('PASSWORD'))
            .map(v => [v.name, { Ref: v.name }])
        )
      ),
    },
  };
}

/**
 * Generate outputs section
 */
function generateOutputs(analysis: AnalysisResult): Record<string, CloudFormationOutput> {
  const outputs: Record<string, CloudFormationOutput> = {};

  // Check what resources we have and add appropriate outputs
  const hasECS = analysis.awsServices.some(s =>
    s.service.toLowerCase().includes('ecs') || s.service.toLowerCase().includes('fargate')
  );
  const hasALB = analysis.awsServices.some(s =>
    s.service.toLowerCase().includes('alb') || s.service.toLowerCase().includes('load balancer')
  );
  const hasRDS = analysis.awsServices.some(s => s.service.toLowerCase().includes('rds'));
  const hasS3 = analysis.awsServices.some(s => s.service.toLowerCase().includes('s3'));

  if (hasALB) {
    outputs.ServiceURL = {
      Description: 'Application URL',
      Value: { 'Fn::GetAtt': ['ALB', 'DNSName'] },
    };
  }

  if (hasECS) {
    outputs.ClusterName = {
      Description: 'ECS Cluster Name',
      Value: { Ref: 'ECSCluster' },
    };
  }

  if (hasRDS) {
    outputs.DatabaseEndpoint = {
      Description: 'Database endpoint',
      Value: { 'Fn::GetAtt': ['RDSInstance', 'Endpoint.Address'] },
    };
  }

  if (hasS3) {
    outputs.AssetsBucket = {
      Description: 'S3 bucket for assets',
      Value: { Ref: 'S3Bucket' },
    };
  }

  return outputs;
}

/**
 * Convert object to YAML string
 */
function toYaml(obj: unknown, indent = 0): string {
  const spaces = '  '.repeat(indent);

  if (obj === null || obj === undefined) {
    return 'null';
  }

  if (typeof obj === 'string') {
    // Check if string needs quoting
    if (obj.includes(':') || obj.includes('#') || obj.includes('\n') || obj === '') {
      return `"${obj.replace(/"/g, '\\"')}"`;
    }
    return obj;
  }

  if (typeof obj === 'number' || typeof obj === 'boolean') {
    return String(obj);
  }

  if (Array.isArray(obj)) {
    if (obj.length === 0) return '[]';
    return obj
      .map(item => {
        const value = toYaml(item, indent + 1);
        if (typeof item === 'object' && item !== null) {
          return `${spaces}- ${value.trim().replace(/^\s+/, '')}`;
        }
        return `${spaces}- ${value}`;
      })
      .join('\n');
  }

  if (typeof obj === 'object') {
    const entries = Object.entries(obj);
    if (entries.length === 0) return '{}';

    return entries
      .map(([key, value]) => {
        if (value === undefined) return '';

        if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
          // Check for CloudFormation intrinsic functions
          const keys = Object.keys(value);
          if (keys.length === 1 && (keys[0] === 'Ref' || keys[0].startsWith('Fn::'))) {
            const fnKey = keys[0];
            const fnValue = (value as Record<string, unknown>)[fnKey];
            if (fnKey === 'Ref') {
              return `${spaces}${key}: !Ref ${fnValue}`;
            } else if (fnKey === 'Fn::Sub') {
              return `${spaces}${key}: !Sub ${toYaml(fnValue)}`;
            } else if (fnKey === 'Fn::GetAtt') {
              const [resource, attr] = fnValue as [string, string];
              return `${spaces}${key}: !GetAtt ${resource}.${attr}`;
            }
          }
        }

        const yamlValue = toYaml(value, indent + 1);
        if (typeof value === 'object' && value !== null) {
          return `${spaces}${key}:\n${yamlValue}`;
        }
        return `${spaces}${key}: ${yamlValue}`;
      })
      .filter(Boolean)
      .join('\n');
  }

  return String(obj);
}
